# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bf397cdfcf66d4211dbefa2b3b59cadb464af4f9252d3bd80886a3fc452b0f0a3368cd0f8907bde4cea8ccc4500159f4373a5532e726a4e60ce05d910e870e94

test:
  secret_key_base: 12fbb8046532421ffd828ba54040c47a4c4af3f575bde3228f417ce067c501eddf7960addde3c66232bdc1b0926d9fef8ff95ada9043a8b6b9574ef7a78a7b14

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
